version: 0.2

phases:
  pre_build:
    commands:
      - aws ecr get-login-password --region ap-southeast-2 | docker login --username AWS --password-stdin 533247146470.dkr.ecr.ap-southeast-2.amazonaws.com
  build:
    commands:
      - docker build -f apps/reservations/Dockerfile -t reservations .
      - docker tag reservations:latest 533247146470.dkr.ecr.ap-southeast-2.amazonaws.com/reservations:latest

      - docker build -f apps/auth/Dockerfile -t auth .
      - docker tag auth:latest 533247146470.dkr.ecr.ap-southeast-2.amazonaws.com/auth:latest

      - docker build -f apps/payments/Dockerfile -t auth .
      - docker tag payments:latest 533247146470.dkr.ecr.ap-southeast-2.amazonaws.com/payments:latest

      - docker build -f apps/payments/Dockerfile -t auth .
      - docker tag notifications:latest 533247146470.dkr.ecr.ap-southeast-2.amazonaws.com/notifications:latest
  post_build:
    commands:
      - docker push 533247146470.dkr.ecr.ap-southeast-2.amazonaws.com/reservations:latest s
      - docker push 533247146470.dkr.ecr.ap-southeast-2.amazonaws.com/auth:latest
      - docker push 533247146470.dkr.ecr.ap-southeast-2.amazonaws.com/payments:latest
      - docker push 533247146470.dkr.ecr.ap-southeast-2.amazonaws.com/notifications:latest
