name: Build and Push Docker Images

on:
  workflow_dispatch:
    
jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1
      with:
        region: ap-southeast-2

    - name: Build and tag reservations image
      run: |
        docker build -f apps/reservations/Dockerfile -t reservations .
        docker tag reservations:latest 533247146470.dkr.ecr.ap-southeast-2.amazonaws.com/reservations:latest

    - name: Build and tag auth image
      run: |
        docker build -f apps/auth/Dockerfile -t auth .
        docker tag auth:latest 533247146470.dkr.ecr.ap-southeast-2.amazonaws.com/auth:latest

    - name: Build and tag payments image
      run: |
        docker build -f apps/payments/Dockerfile -t payments .
        docker tag payments:latest 533247146470.dkr.ecr.ap-southeast-2.amazonaws.com/payments:latest

    - name: Build and tag notifications image
      run: |
        docker build -f apps/notifications/Dockerfile -t notifications .
        docker tag notifications:latest 533247146470.dkr.ecr.ap-southeast-2.amazonaws.com/notifications:latest

    - name: Push reservations image to ECR
      run: |
        docker push 533247146470.dkr.ecr.ap-southeast-2.amazonaws.com/reservations:latest

    - name: Push auth image to ECR
      run: |
        docker push 533247146470.dkr.ecr.ap-southeast-2.amazonaws.com/auth:latest

    - name: Push payments image to ECR
      run: |
        docker push 533247146470.dkr.ecr.ap-southeast-2.amazonaws.com/payments:latest

    - name: Push notifications image to ECR
      run: |
        docker push 533247146470.dkr.ecr.ap-southeast-2.amazonaws.com/notifications:latest
